add jpa autoconfig
youngmonkeys/ezyfox-boot pull request #9
Opened 2021-08-29 16:40 UTC by tvd12

- add jpa auto configuration
- use h2 for unit test

2021-08-30 06:40 UTC, vu-luong requested changes
Em nghĩ nên có  hướng dẫn sử dụng JPA trong README anh ạ. Hiện  tại  mới  chỉ có cho  mongodb.

2021-08-30 15:50 UTC, tvd12 commented
@vu-luong anh đã bổ sung vào readme, review lại giúp anh với nhé

2021-08-31 07:35 UTC, vu-luong requested changes
Anh chưa thêm package vào AllTests.tng.xml ạ

2021-08-31 10:48 UTC, tvd12 commented
@vu-luong anh đã bổ sung, review giúp anh với nhé

2021-08-31 11:10 UTC, vu-luong approved these changes
LGTM!

2021-08-31 11:10 UTC, vu-luong approved these changes
LGTM!

2021-08-31 11:15 UTC, vu-luong approved these changes
LGTM!

2021-08-31 11:19 UTC, vu-luong approved these changes
LGTM!

2021-08-31 11:31 UTC, merged